db.url=jdbc:postgresql://localhost:5432/restaurant
db.username=postgres
db.password=yourpassword
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}